version: '3.3'

services:

  # Crawler
  devita_crawler:
    container_name: devita_crawler
    image: italia/developers-italia-backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - devita_elasticsearch
    networks:
      - overlay

  # Elasticsearch
  devita_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: devita_elasticsearch
    env_file:
      - .env
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/config
    networks:
      - overlay
    ports:
      - 9200:9200
      - 9300:9300

  # Kibana
  devita_kibana:
    container_name: "devita_kibana"
    image: docker.elastic.co/kibana/kibana:6.8.7
    env_file:
        - .env
    depends_on:
      - devita_elasticsearch
    ports:
      - "5601:5601"
    networks:
      - overlay

networks:
  overlay:
